HaberSistemi/HaberSistemi.Admin/Controllers/KategoriController.cs
using HaberSistemi.Admin.Class;
using HaberSistemi.Core.Infrastructure;
using HaberSistemi.Data.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using HaberSistemi.Admin.CustomFilter;

namespace HaberSistemi.Admin.Controllers
{
    public class KategoriController : Controller
    {

        #region Kategori
        private readonly IKategoriRepository _kategoriRepository;

        public KategoriController(IKategoriRepository kategoriRepository)
        {
            _kategoriRepository = kategoriRepository;
        }
        #endregion

        #region Kategori Listeler
        [HttpGet]
        [LoginFilter]
        public ActionResult Index(int Sayfa=1)
        {
            return View(_kategoriRepository.GetAll().OrderByDescending(x => x.ID).ToPagedList(Sayfa , 10));
        }
        #endregion

        #region Kategori Ekle
        [HttpGet]
        [LoginFilter]
        public ActionResult Ekle(int? id)
        {
            if (id == null)
            {
                SetKategoriListele();
                ViewBag.Title = "Kategori Ekle";
                return View();
            }
            else
            {
                SetKategoriListele();
                ViewBag.Title = "Kategori Düzenle";
                Kategori dbKategori = _kategoriRepository.GetById(Convert.ToInt32(id));
                if (dbKategori == null)
                {
                    throw new Exception("Kategori Bulunamadı");
                }

                return View(dbKategori);
            }
            
           
        }

        [HttpPost]
        [LoginFilter]
        public JsonResult Ekle(Kategori kategori)
        {
            try
            {
                _kategoriRepository.Insert(kategori);
                _kategoriRepository.Save();
                return Json(new ResultJson { Success = true, Message = "Kategori Ekleme İşleminiz Başarılı" },JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Loglama yaptırabiliriz
                return Json(new ResultJson { Success = false, Message = "Kategori Eklerken Hata Oluştu" });
            }
            
        }

        #endregion

        #region Kategori Düzenle
        [HttpGet]
        [LoginFilter]
        public ActionResult  Duzenle(int id)
        {
            Kategori dbKategori = _kategoriRepository.GetById(id);
            if (dbKategori == null)
            {
                throw new Exception("Kaktegori Bulunamadı");
            }
            SetKategoriListele();
            return View(dbKategori);
        }

        [HttpPost]
        [LoginFilter]
        public JsonResult Duzenle(Kategori kategori)
        {
       
                Kategori dbKategori = _kategoriRepository.GetById(kategori.ID);
                dbKategori.AktifMi = kategori.AktifMi;
                dbKategori.KategoriAdi = kategori.KategoriAdi;
                dbKategori.ParentID = kategori.ParentID;
                dbKategori.URL = kategori.URL;
            _kategoriRepository.Save();
                return Json(new ResultJson { Success = true, Message = "Düzenleme İşlemi Başarılı" });
          
          //  return Json(new ResultJson { Success = false, Message = "Düzenleme işlemi sırasında bir hata oluştu" });
        }
        #endregion

        #region Sil
        [LoginFilter]
        public JsonResult Sil(int ID)
        {
            Kategori dbKategori = _kategoriRepository.GetById(ID);
            if (dbKategori == null)
            {
                return Json(new ResultJson { Success = true, Message = "Kategori Bulunamadı" });
            }
            _kategoriRepository.Delete(ID);
            _kategoriRepository.Save();

            return Json(new ResultJson { Success= true , Message="Kategori Silme İşleminiz Başarılı"});
        }

        #endregion

        #region Set Kategori
        public void SetKategoriListele(object kategori=null)
        {
            var KategorList = _kategoriRepository.GetMany(x => x.ParentID == 0).ToList();
            ViewBag.Kategori = KategorList;
        }

        #endregion
    }
}

HaberSistemi/HaberSistemi.Admin/Controllers/SliderController.cs
using HaberSistemi.Admin.Class;
using HaberSistemi.Admin.CustomFilter;
using HaberSistemi.Core.Infrastructure;
using HaberSistemi.Data.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using HaberSistemi.Admin.Helper;
using System.IO;


namespace HaberSistemi.Admin.Controllers
{
    public class SliderController : Controller
    {
        private readonly ISliderRepository _sliderRepository;

        public SliderController(ISliderRepository sliderRepository)
        {
            _sliderRepository = sliderRepository;
        }

        //
        // GET: /Slider/
        public ActionResult Index(int Sayfa=1)
        {
            var slider = _sliderRepository.GetAll().OrderByDescending(x => x.ID).ToPagedList(Sayfa, 10);
            return View(slider);
        }

        #region Slider Ekleme
        [HttpGet]
        [LoginFilter]
        public ActionResult Ekle()
        {
            return View();
        }

  
        [HttpPost]
        [LoginFilter]
        public JsonResult Ekle(Slider slider,HttpPostedFileBase ResimURL)
        {
            if (slider.ResimURL != null)
            {
                if (ResimURL.ContentLength > 0)
                {
                    string Dosya = Guid.NewGuid().ToString().Replace("-", "");
                    string Uzanti = System.IO.Path.GetExtension(Request.Files[0].FileName);
                    string ResimYolu = "/External/Slider/" + Dosya + Uzanti;

                    ResimURL.SaveAs(Server.MapPath(ResimYolu));
                    slider.ResimURL = ResimYolu;
                }

                _sliderRepository.Insert(slider);
                try
                {
                    _sliderRepository.Save();
                     return Json(new ResultJson { Success = true, Message = "Slider Ekleme İşleminiz Başarılı :)" });
                }
                catch (Exception ex)
                {
                    
                     return Json(new ResultJson { Success = false, Message = "Slider Ekleme İşleminiz Başarısız !" });
                }
            }
            return Json(new ResultJson { Success = false, Message = "Slider Ekleme İşleminiz Başarısız !" });
        }

      
        #endregion



        #region Slider Düzenle

        [HttpGet]
        [LoginFilter]
        public ActionResult Duzenle(int ID)
        {
            var SliderVarmi = _sliderRepository.GetById(ID);
            if (SliderVarmi != null)
            {
                return View(SliderVarmi);
            }
            return View();
        }


        [HttpPost]
        [LoginFilter]
        public ActionResult Duzenle(Slider slider, HttpPostedFileBase ResimURL)
        {
            if (ModelState.IsValid)
            {
                Slider dbSlider = _sliderRepository.GetById(slider.ID);
                dbSlider.Baslik = slider.Baslik;
                dbSlider.Aciklama = slider.Aciklama;
                dbSlider.AktifMi = slider.AktifMi;
                dbSlider.URL = slider.URL;
                if (ResimURL != null && ResimURL.ContentLength > 0)
                {
                    if (dbSlider.ResimURL != null)
                    {
                        string URL = dbSlider.ResimURL;
                        string resimPath = Server.MapPath(URL);
                        FileInfo files = new FileInfo(resimPath);
                        if (files.Exists)
                        {
                            files.Delete();
                        }
                    }

                    ResimYukle.Resim(ResimURL, slider);
                    dbSlider.ResimURL = slider.ResimURL;
                }

                try
                {
                    _sliderRepository.Save();
                    return Json(new ResultJson { Success = true, Message = slider.Baslik + " Slider Ekleme İşlemi Başarılı" });
                }
                catch (Exception ex)
                {
                    
                    //LogYaz();
                    return Json(new ResultJson { Success = false, Message = slider.Baslik + " Slider Ekleme İşlemi Başarısız !" });
                }
            }
            return View();
        }
        #endregion

        #region Slider Sil
        public JsonResult Sil(Slider slider)
        {
            Slider dbSlider = _sliderRepository.GetById(slider.ID);
            if (dbSlider == null)
            {
                return Json(new ResultJson { Success = false, Message = "Slider Bulunamadı !" });
            }

            try
            {
                  if (dbSlider.ResimURL != null)
            {
                string ResimURL = dbSlider.ResimURL;
                string ResimPath = Server.MapPath(ResimURL);
                FileInfo files = new FileInfo(ResimPath);
                if (files.Exists)
                {
                    files.Delete();
                }
            }
            _sliderRepository.Delete(slider.ID);
            _sliderRepository.Save();
            return Json(new ResultJson { Success = true, Message = "Silme İşleminiz Başarılı" });
            }
            catch (Exception ex)
            {

                return Json(new ResultJson { Success = false, Message = "Silme İşleminiz Başarısız" });
            }
        }
        #endregion
    }
}

HaberSistemi/HaberSistemi.Admin/Views/Shared/_Header.cshtml
<nav class="header-site">
    <div class="container-fluid">
        <!-- Page title and breadcrumb navigation -->
        <div class="page-title">
            <h4><a href="#" id="toggle-menu"><i class="typcn typcn-th-menu"></i></a> <span>Haber Portalı - Yönetim Sayfası</span></h4>
            <nav>
                <a href="@Url.Action("Index","Home")">Anasayfa</a>
                <span class="typcn typcn-chevron-right"></span>
                <a href="#">@ViewBag.Title</a>
            </nav>
        </div>
        <!-- /Page title and breadcrumb navigation -->
        <!-- Header navigation / icons -->
        <ul class="header-nav navbar-right">
            <!-- Messages -->
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="typcn typcn-messages"></span></a>
                <span class="badge">3</span>
                <div class="dropdown-menu panel panel-messages dropdown-arrow pull-right">
                    <div class="panel-heading">MESSAGES <span class="badge pull-right bg-orange">NEW</span></div>
                    <div class="panel-body scrollbox">
                        <ul class="chat">
                            <li class="left clearfix">
                                <a href="#">
                                    <span class="chat-img pull-left">
                                        <img src="placeholders/user1.jpg" alt="User Avatar" class="img-circle">
                                    </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font">Jon Bateman</strong>
                                            <small class="pull-right text-muted">
                                                <span class="glyphicon glyphicon-time"></span>12 mins ago
                                            </small>
                                        </div>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibend...
                                        </p>
                                    </div>
                                </a>
                            </li>
                            <li class="left clearfix">
                                <a href="#">
                                    <span class="chat-img pull-left">
                                        <img src="placeholders/user2.jpg" alt="User Avatar" class="img-circle">
                                    </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font">Sam Smalls</strong>
                                            <small class="pull-right text-muted">
                                                <span class="glyphicon glyphicon-time"></span>12 mins ago
                                            </small>
                                        </div>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibend...
                                        </p>
                                    </div>
                                </a>
                            </li>
                            <li class="left clearfix">
                                <a href="#">
                                    <span class="chat-img pull-left">
                                        <img src="placeholders/user1.jpg" alt="User Avatar" class="img-circle">
                                    </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font">The Flash</strong>
                                            <small class="pull-right text-muted">
                                                <span class="glyphicon glyphicon-time"></span>12 mins ago
                                            </small>
                                        </div>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibend...
                                        </p>
                                    </div>
                                </a>
                            </li>
                            <li class="left clearfix">
                                <a href="#">
                                    <span class="chat-img pull-left">
                                        <img src="placeholders/user2.jpg" alt="User Avatar" class="img-circle">
                                    </span>
                                    <div class="chat-body clearfix">
                                        <div class="header">
                                            <strong class="primary-font">Bruce Nolan</strong>
                                            <small class="pull-right text-muted">
                                                <span class="glyphicon glyphicon-time"></span>12 mins ago
                                            </small>
                                        </div>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibend...
                                        </p>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <footer class="panel-footer text-center">
                        <a href="#">View all messages</a>
                    </footer>
                </div>
            </li>
            <!-- /Messages -->
            <!-- Notifications -->
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="typcn typcn-bell"></span></a>
                <div class="dropdown-menu panel panel-notifications dropdown-arrow pull-right">
                    <div class="panel-heading">NOTIFICATIONS</div>
                    <div class="panel-body scrollbox">
                        <ul>
                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">
                                            <i class="typcn typcn-heart bg-red"></i>
                                            New likes
                                        </span>
                                        <span class="badge badge-gray pull-right">22</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">
                                            <i class="typcn typcn-user bg-blue"></i>
                                            New users
                                        </span>
                                        <span class="badge badge-gray pull-right">6</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">
                                            <i class="typcn typcn-image bg-green"></i>
                                            New pictures
                                        </span>
                                        <span class="badge badge-gray pull-right">125</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">
                                            <i class="typcn typcn-heart bg-orange"></i>
                                            New likes
                                        </span>
                                        <span class="badge badge-gray pull-right">22</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">
                                            <i class="typcn typcn-user bg-purple"></i>
                                            New users
                                        </span>
                                        <span class="badge badge-gray pull-right">6</span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">
                                            <i class="typcn typcn-image bg-yellow"></i>
                                            New pictures
                                        </span>
                                        <span class="badge badge-gray pull-right">125</span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
            <!-- /Notifications -->
            <!-- Profile -->
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">@Session["KullaniciAdi"]</a>
                <ul class="dropdown-menu dropdown-arrow pull-right">
                    <li><a href="#"><span class="typcn typcn-edit"></span> Edit profile</a></li>
                    <li><a href="#"><span class="typcn typcn-cog"></span> Settings</a></li>
                    <li><a href="#"><span class="typcn typcn-contacts"></span> Contacts</a></li>
                    <li class="divider"></li>
                    <li><a href="@Url.Action("Cikis","Account")"><span class="typcn typcn-power"></span> Çıkış</a></li>
                </ul>
            </li>
            <!-- /Profile -->
        </ul>
        <!-- /Header navigation / icons -->
    </div>
</nav>

HaberSistemi/HaberSistemi.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800,400italic%7cMontserrat:400,700" rel="stylesheet" type="text/css">
    <!-- Icons -->
  
    <link href="~/Content/typicons.min.css" rel="stylesheet">
   
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <!-- iCheck - Custom radio/check input -->
    <link href="~/Content/icheck/minimal.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">

    <!-- Footable plugin -->
    <link href="~/Content/plugins.min.css" rel="stylesheet">

    <link href="~/Content/sweetalert.css" rel="stylesheet" />
    <!-- Template -->
    <link href="~/Content/main.css" rel="stylesheet">

    <link href="~/Content/bootstrap-tagsinput.css" rel="stylesheet" />
    <script src="~/Scripts/plugins/jquery.min.js"></script> 
    <!--[if lt IE 9]>
      <script src="js/plugins/shiv.min.js"></script>
      <script src="js/plugins/respond.min.js"></script>
      <script src="js/plugins/excanvas.min.js"></script>
    <![endif]-->
</head>
<body>

    <!-- Page container -->
    <div class="page-container">
        <!-- Sidebar -->
        @Html.Partial("_Sidebar")
        <!-- /Sidebar -->
        <!-- Content -->
        <div id="content">
            <!-- Header -->
@Html.Partial("_Header")
            <!-- /Header -->
            <!-- Content start -->
           
            @RenderBody()
        </div>
        <!-- /Content -->
    </div>
    <!-- /Page container -->
    <!-- PLUGINS ALL -->
 


  

    <script src="~/Scripts/plugins/modernizr.min.js"></script>
    <!-- Bootstrap core -->
    <script src="~/Scripts/plugins/bootstrap.min.js"></script>

    <!-- Custom scrollbar -->
    <script src="~/Scripts/plugins/enscroll.min.js"></script>
    <!-- Dynamic tables -->
    <script src="~/Scripts/plugins/footable.min.js"></script>
    <!-- Knob / Donut charts -->
    <script src="~/Scripts/plugins/knob.min.js"></script>
    <!-- Rickshaw graphs & charts -->
    <script src="~/Scripts/plugins/sparkline.min.js"></script>
    <script src="~/Scripts/plugins/rickshaw/d3.v3.js"></script>
    <script src="~/Scripts/plugins/rickshaw/rickshaw.min.js"></script>
    <!-- Flot -->
    <script src="~/Scripts/plugins/flot.min.js"></script>
    <!-- Custom checkboxes and radio input -->
    <script src="~/Scripts/plugins/icheck.min.js"></script>
   
    <!-- Site -->
    <script src="~/Scripts/main.js"></script>

    <script src="~/Scripts/Global.js"></script>
    <script src="~/Scripts/bootstrap-tagsinput.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
    <script src="~/Scripts/notify.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/sweetalert.min.js"></script>
</body>

</html>

HaberSistemi/HaberSistemi.Admin/Views/Shared/_Sidebar.cshtml
<aside id="sidebar">
    <!-- Sidebar header -->
    <header class="sidebar-header">
        <h1><img src="img/logo.png" alt="Saltkin"></h1>
        <a href="#" id="make-compact"><span class="typcn typcn-th-menu"></span></a>
        <a href="#" id="hide-menu"><span class="fa fa-caret-square-o-left"></span></a>
    </header>
    <!-- /Sidebar header -->
    <!-- Sidebar group -->
    <ul class="sidebar-group">
        <li class="sidebar-group-header">Menü</li>
        <li>
            <a href="@Url.Action("Index","Home")"><i class="typcn typcn-home"></i> <span>Anasayfa</span></a>
            <div class="sidebar-link-addon"><span class="badge bg-green">Yeni</span></div>
        </li>
        <li class="has-submenu">
            <a href="#"><i class="typcn typcn-tabs-outline"></i> <span>Haber Yönetimi</span></a>
            <div class="sidebar-link-addon"><i class="typcn typcn-plus"></i></div>
            <!-- Sidebar submenu -->
            <ul class="sidebar-submenu">
                <li><a href="@Url.Action("Index","Haber")">Haber Listele</a></li>
                <li><a href="@Url.Action("Ekle","Haber")">Haber Ekle</a></li>


            </ul>
            <!-- /Sidebar submenu -->
        </li>
        <li class="has-submenu">
            <a href="#"><i class="typcn typcn-tabs-outline"></i> <span>Kategori Yönetimi</span></a>
            <div class="sidebar-link-addon"><i class="typcn typcn-plus"></i></div>
            <!-- Sidebar submenu -->
            <ul class="sidebar-submenu">
                <li><a href="@Url.Action("Index","Kategori")">Kategori Listele</a></li>
                <li><a href="@Url.Action("Ekle","Kategori")">Kategori Ekle</a></li>
             
                
            </ul>
            <!-- /Sidebar submenu -->
        </li>
        <li class="has-submenu">
            <a href="#"><i class="typcn typcn-tabs-outline"></i> <span>Slider Yönetimi</span></a>
            <div class="sidebar-link-addon"><i class="typcn typcn-plus"></i></div>
            <!-- Sidebar submenu -->
            <ul class="sidebar-submenu">
                <li><a href="@Url.Action("Index","Slider")">Slider Listele</a></li>
                <li><a href="@Url.Action("Ekle", "Slider")">Slider Ekle</a></li>


            </ul>
            <!-- /Sidebar submenu -->
        </li>
        <li class="has-submenu">
            <a href="#"><i class="typcn typcn-tabs-outline"></i> <span>Kullanıcı Yönetimi</span></a>
            <div class="sidebar-link-addon"><i class="typcn typcn-plus"></i></div>
            <!-- Sidebar submenu -->
            <ul class="sidebar-submenu">
                <li><a href="@Url.Action("Index", "Account")">Kullanıcı Listele</a></li>
                <li><a href="@Url.Action("Kayit", "Account")">Kullanici Ekle</a></li>


            </ul>
            <!-- /Sidebar submenu -->
        </li>
    </ul>
    <!-- /Sidebar group -->
    


    <!-- /Sidebar panel -->
</aside>